задание 1

In [38]:
import pandas as pd

titanic = pd.read_csv('train.csv')

display(titanic.head(10))
display(titanic.tail())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

задание 2

In [135]:
titanic.info()
titanic.describe()
titanic.describe(include=['object'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

                       Name   Sex  Ticket Cabin Embarked
count                   891   891     891   204      891
unique                  891     2     681   147        3
top     Dooley, Mr. Patrick  male  347082    G6        S
freq                      1   577       7     4      646

задание 3

In [96]:
embarked_series = pd.Series(titanic['Embarked']).head()
embarked_series.index=["Первый", "Второй", "Третий", "Четвертый", "Пятый"]
display(embarked_series)
display(embarked_series.loc[["Третий", "Четвертый", "Пятый"]])
display(embarked_series.iloc[[0, 1]])

Первый       S
Второй       C
Третий       S
Четвертый    S
Пятый        S
Name: Embarked, dtype: object

Третий       S
Четвертый    S
Пятый        S
Name: Embarked, dtype: object

Первый    S
Второй    C
Name: Embarked, dtype: object

задание 4

In [64]:
display(titanic.Age.mean())
display(titanic.Fare.min())
display(titanic.Fare.max())
display(titanic.Age.std())

np.float64(29.69911764705882)

0.0

512.3292

14.526497332334044

задание 5

In [93]:
display(titanic[titanic.Age > 30])
display(titanic[titanic.Fare > titanic.Fare.mean()])
filtered1 = titanic[(titanic.Pclass == 1) & (titanic.Sex == 'female')]
display(filtered1)
display(filtered1.Age.mean())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

np.float64(34.61176470588235)

задание 6

In [97]:
filtered2 = titanic[(titanic.Survived == 1) & (titanic.Age < 18)]
display(filtered2)
display(filtered2.Fare.mean())
display(len(filtered2))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
830,831,1,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.00,1,0,2659,14.4542,NaN,C
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
853,854,1,1,"Lines, Miss. Mary Conover",female,16.00,0,1,PC 17592,39.4000,D28,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.00,0,0,2667,7.2250,NaN,C

np.float64(34.857309836065575)

61

задание 7

In [119]:
grouped1 = titanic.groupby('Pclass')[['Age', 'Fare']].agg({'Age': 'mean', 'Fare': ['count', 'mean']}).sort_values(by = ('Fare', 'mean'), ascending = False)
display(grouped1)

              Age  Fare
             mean count       mean
Pclass
1       38.233441   216  84.154687
2       29.877630   184  20.662183
3       25.140620   491  13.675550

задание 8

In [123]:
titanic.pivot_table(values='Survived', index='Pclass', columns='Sex', aggfunc='mean')

Sex       female      male
Pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

задание 9

In [138]:
titanic.isnull().sum()
titanic.isnull().sum() / len(titanic) * 100

embarked_top = titanic.Embarked.describe(include=['object'])['top']
titanic['Embarked'] = titanic['Embarked'].fillna(embarked_top)
age_median = titanic.Age.describe()['50%']
titanic['Age'] = titanic['Age'].fillna(age_median)

display(titanic.duplicated(subset=['PassengerId']).sum())
titanic.drop_duplicates(subset=['PassengerId'], keep='first')

np.int64(0)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [137]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

задание 10

In [141]:
titanic['FamilySize'] = titanic['SibSp'] + titanic['Parch'] + 1
titanic['IsAlone'] = titanic['FamilySize'].apply(lambda x: 1 if x == 1 else 0)
titanic['AgeGroup'] = pd.cut(titanic['Age'],
                             bins=[0, 12, 18, 35, 60, 100],
                             labels=['ребёнок', 'подросток', 'молодой', 'взрослый','пожилой'])
display(titanic)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,IsAlone,AgeGroup
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,0,молодой
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,0,взрослый
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,1,молодой
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,0,молодой
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,1,молодой
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1,1,молодой
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,1,молодой
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S,4,0,молодой
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,1,молодой
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1,1,молодой

In [142]:
age_analysis = titanic.groupby('AgeGroup')[['Survived', 'Fare']].agg({'Survived': 'mean', 'Fare': ['mean', 'count']})
display(age_analysis)

/tmp/ipykernel_948/467736969.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  age_analysis = titanic.groupby('AgeGroup')[['Survived', 'Fare']].agg({'Survived': 'mean', 'Fare': ['mean', 'count']})

           Survived       Fare
               mean       mean count
AgeGroup
ребёнок    0.579710  31.536352    69
подросток  0.428571  33.451313    70
молодой    0.353271  27.356166   535
взрослый   0.400000  44.259658   195
пожилой    0.227273  41.371214    22

In [143]:
titanic.pivot_table(values='Survived',
 index='AgeGroup')

/tmp/ipykernel_948/3383492716.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table(values='Survived',

           Survived
AgeGroup
ребёнок    0.579710
подросток  0.428571
молодой    0.353271
взрослый   0.400000
пожилой    0.227273

Задание 11

In [149]:
port_counts = titanic.groupby('Embarked')['PassengerId'].count().sort_values(ascending=False)
display(port_counts)

Embarked
S    646
C    168
Q     77
Name: PassengerId, dtype: int64

In [147]:
embarked_stats = titanic.groupby('Embarked').agg({'Age': 'mean', 'Fare': 'mean', 'Survived': 'mean', 'Pclass': lambda x: (x == 1).mean()})
display(embarked_stats)

                Age       Fare  Survived    Pclass
Embarked
C         30.178095  59.954144  0.553571  0.505952
Q         28.032468  13.276030  0.389610  0.025974
S         29.307663  27.243651  0.339009  0.199690

Задание 12

In [169]:
grouped_by_familysize = titanic.groupby('FamilySize').agg(Доля_выживших=('Survived', 'mean'),
                                                          Средний_возраст=('Age', 'mean'),
                                                          Средняя_стоимость_билета=('Fare', 'mean'),
                                                          Количество_пассажиров=('PassengerId', 'count'))
display(grouped_by_familysize)

,Доля_выживших,Средний_возраст,Средняя_стоимость_билета,Количество_пассажиров
FamilySize,,,,
1,0.303538,31.175047,21.242689,537
2,0.552795,30.928075,49.894129,161
3,0.578431,26.209118,39.692482,102
4,0.724138,18.945517,54.864510,29
5,0.200000,22.733333,58.094453,15
6,0.136364,18.409091,73.722727,22
7,0.333333,15.166667,29.366667,12
8,0.000000,15.666667,46.900000,6
11,0.000000,28.000000,69.550000,7

In [173]:
filtered_familysize = grouped_by_familysize[grouped_by_familysize['Количество_пассажиров'] > 10]
sorted_familysize = filtered_familysize.sort_values('Доля_выживших', ascending = False)
display(sorted_familysize)

,Доля_выживших,Средний_возраст,Средняя_стоимость_билета,Количество_пассажиров
FamilySize,,,,
4,0.724138,18.945517,54.864510,29
3,0.578431,26.209118,39.692482,102
2,0.552795,30.928075,49.894129,161
7,0.333333,15.166667,29.366667,12
1,0.303538,31.175047,21.242689,537
5,0.200000,22.733333,58.094453,15
6,0.136364,18.409091,73.722727,22